const PHASE = {
    LOBBY: 'LOBBY',
    LOADING: 'LOADING',
    STAGE_SELECT: 'STAGE_SELECT',
    PARTY_BOX: 'PARTY_BOX',
    BUILD: 'BUILD',
    RACE: 'RACE',
    ROUND_RESULTS: 'ROUND_RESULTS',
    FINAL_RESULTS: 'FINAL_RESULTS'
};
const CLIENT_MESSAGE_PHASES = {
    JOIN_ROOM: [PHASE.LOBBY],
    SET_COLOR_REQUEST: [PHASE.LOBBY],
    START_MATCH_REQUEST: [PHASE.LOBBY],
    CLIENT_READY: [PHASE.LOADING],
    STAGE_CURSOR_MOVE: [PHASE.STAGE_SELECT],
    STAGE_PICK_REQUEST: [PHASE.STAGE_SELECT],
    PARTY_CURSOR_MOVE: [PHASE.PARTY_BOX],
    PARTY_PICK_REQUEST: [PHASE.PARTY_BOX],
    BUILD_CURSOR_MOVE: [PHASE.BUILD],
    PLACE_PIECE_REQUEST: [PHASE.BUILD],
    INPUT_FRAME: [PHASE.RACE],
    POSITION_SNAPSHOT: [PHASE.RACE, PHASE.STAGE_SELECT],
    TILE_UPDATE: [PHASE.RACE],
    FINISH_OBSERVED: [PHASE.RACE],
    ELIMINATION_OBSERVED: [PHASE.RACE],
    CONTINUE_REQUEST: [PHASE.ROUND_RESULTS],
    CHAT_MESSAGE: Object.values(PHASE)
};

const TOTAL_ROUNDS = 10;
function getPartyBoxSlotCount(playerCount) {
    return Math.ceil(1.5 * playerCount);
}

const STAGE_TIME_LIMIT = 12;
const STAGE_VOTE_STAND_SECONDS = 3;
const PARTY_TIME_LIMIT = 12;
const BUILD_TIME_LIMIT = 20;
const RACE_TIME_LIMIT = 60;
const MIN_PLAYERS_TO_START = 1;
const MAX_PLAYERS = 6;
const FINISH_TICK_TOLERANCE = 2;
const LOADING_BARRIER_TIMEOUT_MS = 15000;
const ROUND_END_DELAY_MS = 3000;
const CHAT_MESSAGE_MAX_LENGTH = 140;

module.exports = {
    PHASE,
    CLIENT_MESSAGE_PHASES,
    TOTAL_ROUNDS,
    getPartyBoxSlotCount,
    STAGE_TIME_LIMIT,
    STAGE_VOTE_STAND_SECONDS,
    PARTY_TIME_LIMIT,
    BUILD_TIME_LIMIT,
    RACE_TIME_LIMIT,
    MIN_PLAYERS_TO_START,
    MAX_PLAYERS,
    FINISH_TICK_TOLERANCE,
    LOADING_BARRIER_TIMEOUT_MS,
    ROUND_END_DELAY_MS,
    CHAT_MESSAGE_MAX_LENGTH
};